# Generated by Django 4.1 on 2022-11-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searcher", "0003_hist"),
    ]

    operations = [
        migrations.CreateModel(
            name="qas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("a1", models.TextField()),
                ("a2", models.TextField()),
                ("a3", models.TextField()),
                ("a4", models.TextField()),
                ("a5", models.TextField()),
                ("cx1", models.TextField()),
                ("cx2", models.TextField()),
                ("cx3", models.TextField()),
                ("cx4", models.TextField()),
                ("cx5", models.TextField()),
                ("t1", models.TextField()),
                ("t2", models.TextField()),
                ("t3", models.TextField()),
                ("t4", models.TextField()),
                ("t5", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="qa",
        ),
    ]
